# Compiler and flags
CC = gcc
CFLAGS = -Wall -Wextra -g

# Target exec name
TARGET = lab2

# Source files
SRC = shellA.c

# Compile executable
$(TARGET) : $(SRC)
	$(CC) $(CFLAGS) -o $(TARGET) $(SRC)

# Clean up
clean:
	rm -f $(TARGET)

