import java.io.File;
import java.io.FileWriter;
import java.io.IOException;

import components.simplereader.SimpleReader;
import components.simplereader.SimpleReader1L;
import components.simplewriter.SimpleWriter;
import components.simplewriter.SimpleWriter1L;
import components.xmltree.XMLTree;
import components.xmltree.XMLTree1;

/**
 * Takes an RSS feed input and outputs a page with links to each item
 *
 * @author Gage Farmer
 *
 */
public final class RSSAggregator {

    /**
     * No argument constructor--private to prevent instantiation.
     */
    private RSSAggregator() {
    }

    static String file = "page.html";
    File page = new File(file);

    /**
     * Outputs the "opening" tags in the generated HTML file. These are the
     * expected elements generated by this method:
     *
     * <html> <head> <title>the channel tag title as the page title</title>
     * </head> <body>
     * <h1>the page title inside a link to the <channel> link</h1>
     * <p>
     * the channel description
     * </p>
     * <table border="1">
     * <tr>
     * <th>Date</th>
     * <th>Source</th>
     * <th>News</th>
     * </tr>
     *
     * @param channel
     *            the channel element XMLTree
     * @param out
     *            the output stream
     * @updates out.content
     * @requires [the root of channel is a <channel> tag] and out.is_open
     * @ensures out.content = #out.content * [the HTML "opening" tags]
     */
    private static void outputHeader(XMLTree channel, SimpleWriter out,
            FileWriter writer) {

        try {

            writer.write("<html> <head> <title>"
                    + channel.child(getChildElement(channel, "title")).child(0)
                    + "</title>" + "\n");
            writer.write("</head> <body>" + "\n");
        } catch (IOException e) {
            System.out.println("Error in outputHeader");
            e.printStackTrace();
        }
    }

    /**
     * Outputs the "closing" tags in the generated HTML file. These are the
     * expected elements generated by this method:
     *
     * </table>
     * </body> </html>
     *
     * @param out
     *            the output stream
     * @updates out.contents
     * @requires out.is_open
     * @ensures out.content = #out.content * [the HTML "closing" tags]
     */
    private static void outputFooter(SimpleWriter out, FileWriter writer) {
        try {
            writer.write("</table>" + "\n");
            writer.write("</body> </html>" + "\n");
        } catch (IOException e) {
            System.out.println("Error in outputFooter");
            e.printStackTrace();
        }

    }

    /**
     * Processes one XML RSS (version 2.0) feed from a given URL converting it
     * into the corresponding HTML output file.
     *
     * @param url
     *            the URL of the RSS feed
     * @param file
     *            the name of the HTML output file
     * @param out
     *            the output stream to report progress or errors
     * @updates out.content
     * @requires out.is_open
     * @ensures <pre>
     * [reads RSS feed from url, saves HTML document with table of news items
     *   to file, appends to out.content any needed messages]
     * </pre>
     */
    private static void processFeed(String url, String file, SimpleWriter out) {
        XMLTree urlTree = new XMLTree1(url);

        try {
            FileWriter writer = new FileWriter(file);
            writer.write("<td><a href=\""
                    + urlTree.child(getChildElement(urlTree, "feed"))
                            .attributeValue("url")
                    + "\">" + urlTree.child(getChildElement(urlTree, "feed"))
                            .attributeValue("name")
                    + "</td>" + "\n");

        } catch (IOException e) {
            // TODO Auto-generated catch block
            e.printStackTrace();
        }

    }

    /**
     * Finds the first occurrence of the given tag among the children of the
     * given {@code XMLTree} and return its index; returns -1 if not found.
     *
     * @param xml
     *            the {@code XMLTree} to search
     * @param tag
     *            the tag to look for
     * @return the index of the first child of type tag of the {@code XMLTree}
     *         or -1 if not found
     * @requires [the label of the root of xml is a tag]
     * @ensures <pre>
     * getChildElement =
     *  [the index of the first child of type tag of the {@code XMLTree} or
     *   -1 if not found]
     * </pre>
     */
    private static int getChildElement(XMLTree xml, String tag) {

        boolean found = false;
        XMLTree temp = xml;
        int i = 0;

        while (!found) {
            if (xml.child(i).label() == tag) {
                found = true;
            } else {
                i++;
            }
        }

        return i;
    }

    /**
     * Main method.
     *
     * @param args
     *            the command line arguments
     * @throws IOException
     */
    public static void main(String[] args) throws IOException {
        SimpleReader in = new SimpleReader1L();
        SimpleWriter out = new SimpleWriter1L();
        String url;
        FileWriter writer = new FileWriter(file);

        System.out.print("Enter an RSS file name: ");
        url = in.nextLine();
        XMLTree urlTree = new XMLTree1(url);

        outputHeader(urlTree, out, writer);
        //processFeed(url, file, out);
        //outputFooter(out, writer);

        in.close();
        out.close();
    }

}
